"""add asset_relationships and scim_external_id

Revision ID: 0b1a7574522d
Revises: ddfaea332ea6
Create Date: 2026-03-05 09:06:55.491947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b1a7574522d'
down_revision: Union[str, None] = 'ddfaea332ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_relationships',
    sa.Column('source_asset_id', sa.UUID(), nullable=False),
    sa.Column('target_asset_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_asset_id', 'target_asset_id', 'relationship_type', name='uq_asset_rel_src_tgt_type')
    )
    op.create_index(op.f('ix_asset_relationships_source_asset_id'), 'asset_relationships', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_target_asset_id'), 'asset_relationships', ['target_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_tenant_id'), 'asset_relationships', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('scim_external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_scim_external_id'), 'users', ['scim_external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_scim_external_id'), table_name='users')
    op.drop_column('users', 'scim_external_id')
    op.drop_index(op.f('ix_asset_relationships_tenant_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_target_asset_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_source_asset_id'), table_name='asset_relationships')
    op.drop_table('asset_relationships')
    # ### end Alembic commands ###
