"""add webhooks finding_comments framework_mappings assigned_to

Revision ID: 2b11abce3513
Revises: 617bda18ff21
Create Date: 2026-03-04 19:39:29.356775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b11abce3513'
down_revision: Union[str, None] = '617bda18ff21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=200), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_tenant_id'), 'webhooks', ['tenant_id'], unique=False)
    op.create_table('finding_comments',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_comments_finding_id'), 'finding_comments', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_comments_user_id'), 'finding_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_assets_resource_type'), 'assets', ['resource_type'], unique=False)
    op.add_column('controls', sa.Column('framework_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('findings', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.create_index('ix_findings_account_status', 'findings', ['cloud_account_id', 'status'], unique=False)
    op.create_index(op.f('ix_findings_asset_id'), 'findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_findings_assigned_to'), 'findings', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_findings_cloud_account_id'), 'findings', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_findings_control_id'), 'findings', ['control_id'], unique=False)
    op.create_index('ix_findings_last_evaluated', 'findings', ['last_evaluated_at'], unique=False)
    op.create_index('ix_findings_status', 'findings', ['status'], unique=False)
    op.create_foreign_key(None, 'findings', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.drop_index('ix_findings_status', table_name='findings')
    op.drop_index('ix_findings_last_evaluated', table_name='findings')
    op.drop_index(op.f('ix_findings_control_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_cloud_account_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_assigned_to'), table_name='findings')
    op.drop_index(op.f('ix_findings_asset_id'), table_name='findings')
    op.drop_index('ix_findings_account_status', table_name='findings')
    op.drop_column('findings', 'assigned_to')
    op.drop_column('controls', 'framework_mappings')
    op.drop_index(op.f('ix_assets_resource_type'), table_name='assets')
    op.drop_index(op.f('ix_finding_comments_user_id'), table_name='finding_comments')
    op.drop_index(op.f('ix_finding_comments_finding_id'), table_name='finding_comments')
    op.drop_table('finding_comments')
    op.drop_index(op.f('ix_webhooks_tenant_id'), table_name='webhooks')
    op.drop_table('webhooks')
    # ### end Alembic commands ###
