"""add slack_integrations jira_integrations tables and finding jira columns

Revision ID: 5c2e594032eb
Revises: fb5121fd2df4
Create Date: 2026-03-05 07:57:51.318165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c2e594032eb'
down_revision: Union[str, None] = 'fb5121fd2df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_integrations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('api_token_encrypted', sa.Text(), nullable=False),
    sa.Column('project_key', sa.String(length=20), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_integrations_tenant_id'), 'jira_integrations', ['tenant_id'], unique=False)
    op.create_table('slack_integrations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_integrations_tenant_id'), 'slack_integrations', ['tenant_id'], unique=False)
    op.add_column('findings', sa.Column('jira_ticket_key', sa.String(length=50), nullable=True))
    op.add_column('findings', sa.Column('jira_ticket_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'jira_ticket_url')
    op.drop_column('findings', 'jira_ticket_key')
    op.drop_index(op.f('ix_slack_integrations_tenant_id'), table_name='slack_integrations')
    op.drop_table('slack_integrations')
    op.drop_index(op.f('ix_jira_integrations_tenant_id'), table_name='jira_integrations')
    op.drop_table('jira_integrations')
    # ### end Alembic commands ###
