"""add custom_dashboards and sso_configs tables

Revision ID: ddfaea332ea6
Revises: 6409be9080bb
Create Date: 2026-03-05 08:41:20.766192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddfaea332ea6'
down_revision: Union[str, None] = '6409be9080bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_configs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('issuer_url', sa.String(length=500), nullable=False),
    sa.Column('metadata_url', sa.String(length=500), nullable=True),
    sa.Column('domain_restriction', sa.String(length=255), nullable=True),
    sa.Column('auto_provision', sa.Boolean(), nullable=False),
    sa.Column('default_role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sso_configs_tenant_id'), 'sso_configs', ['tenant_id'], unique=True)
    op.create_table('custom_dashboards',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_dashboards_tenant_id'), 'custom_dashboards', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_custom_dashboards_user_id'), 'custom_dashboards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_dashboards_user_id'), table_name='custom_dashboards')
    op.drop_index(op.f('ix_custom_dashboards_tenant_id'), table_name='custom_dashboards')
    op.drop_table('custom_dashboards')
    op.drop_index(op.f('ix_sso_configs_tenant_id'), table_name='sso_configs')
    op.drop_table('sso_configs')
    # ### end Alembic commands ###
